version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - "9000:9000"
    networks:
      - laravel_network
    depends_on:
      - db

  webserver:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: laravel_postgres
    environment:
      POSTGRES_USER: # YOUR_POSTGRES_DATABASE_USERNAME
      POSTGRES_PASSWORD: # YOUR_POSTGRES_DATABASE_PASSWORD
      POSTGRES_DB: # YOUR_POSTGRES_DATABASE_NAME
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
